### ISSUE TITLE
Download stuck in long list

### ISSUE THREAD

**Issue by Jinestic** [GrayGalaxy/jiosaavn-downloader#15]
### What happened?

Download stuck in long list (repeat issue, as this was fixed in v0.7x) 

- URL: https://www.jiosaavn.com/s/playlist/0f8d02afa160d2ea7d9ef4bedf677fd9/Test/jEvn0v2rde8V3Xpvr9dnYw__
- Browser: Chrome

also can't select extreme quality while streaming (it shows Pro only)

### Reproduction steps

Try to download this playlist: https://www.jiosaavn.com/s/playlist/0f8d02afa160d2ea7d9ef4bedf677fd9/Test/jEvn0v2rde8V3Xpvr9dnYw__

It will start downloading in background but never creates final zip file. Gets stuck in downloading loop.

Btw if I remember correctly we had download progress bar in earlier version right? something like 8/300 downloaded, crating zip etc...in left bottom popup. It is no longer present in latest version 22.2.14, so request you to bring it back if possible.

Regarding streaming quality:
![image](https://user-images.githubusercontent.com/35566052/153991488-6adbbf5a-e4e1-4944-8974-115668a1d290.png)

**Comment by GrayGalaxy** [comment]
@jineshpatel30 thanks for creating this issue.

I found that the playlist has no Cover Image, and that's the problem, not being a long list, this breaks the process of zipping the file.\
It was a enormous list though 😵‍💫.

The problem is in the downloading sequence. I currently did not implemented any fallback method for Albums or Playlist with no images. This problem will be fixed soon.

**Comment by GrayGalaxy** [comment]
And if you want to download in Extreme (320 kbps) refer to issue #14.

**Comment by jineshpatel30** [comment]
> If you want to download in Extreme (320 kbps) refer to issue #14, or checkout the [this section](https://github.com/GrayGalaxy/jiosaavn-downloader#customizing-the-extension-) in readme.

No I understand how to change the extension option to select 320/extreme download and it works.

I was reporting regarding streaming at 320/extreme. While downloading at 320 works, streaming at 320 no longer works. It shows Pro only.

Not that important for me, but just reporting as I noticed. I believe streaming at 320 was working in v0.7x, not sure though.

**Comment by jineshpatel30** [comment]
> @jineshpatel30 thanks for creating this issue.
> 
> I found that the playlist has no Cover Image, and that's the problem, not being a long list, this breaks the process of zipping the file. It was a enormous list though 😵‍💫.
> 
> The problem is in the downloading sequence. I currently did not implemented any fallback method for Albums or Playlist with no images. This problem will be fixed soon.

Great, seems an easy fix, and yes indeed it's long list😅

Thanks again for your work and support!

**Comment by GrayGalaxy** [comment]
> No I understand how to change the extension option to select 320/extreme download and it works.
> I was reporting regarding streaming at 320/extreme. While downloading at 320 works, streaming at 320 no longer works. It shows Pro only. 
> Not that important for me, but just reporting as I noticed. I believe streaming at 320 was working in v0.7x, not sure though.

Not sure about that, I never intent to enable streaming at 320.

Thanks for letting me know anyway, I will look into that and go through the previous builds, and possibly try to recreate the feature again.

**Comment by GrayGalaxy** [comment]
The issue is fixed. it was sort of related to #5, that was fixed in pervious versions.

**Comment by Jinestic** [comment]
> @Jinestic The issue is fixed. it was sort of related to #5, that was fixed in pervious versions.
> 
> And also thanks for the hell of a long playlist, It gave me the inspiration for implementing concurrent download.

@GrayGalaxy Not sure if this is related to fix or concurrent download but now it is downloading at very slow speed ~1-2mbps vs 40-50mbps in v22.2.14.

**Comment by Jinestic** [comment]
> The concurrent download is not implemented yet.
> 
> And talking about metatags with node.js it is virtually impossible to add metatags to mp4 or m4a file format. There is only one possible way (as far I know), that we can convert it to mp3 (with FFMPEG) then add meta tags. Currently I don't know how to implement that.

Okay, may be Jio server slowed down my speed due to multiple requests, as I checked on YouTube and other domains and they are working fine with ~50mbps.

Will try after sometime, thanks!

**Comment by Jinestic** [comment]
> The concurrent download is not implemented yet.
> 
> And talking about metatags with node.js it is virtually impossible to add metatags to mp4 or m4a file format. There is only one possible way (as far I know), that we can convert it to mp3 (with FFMPEG) then add meta tags. Currently I don't know how to implement that.

@GrayGalaxy not sure if you are aware but this project seems interesting for M4A/MP4 metadata, and might be useful.
https://github.com/wez/atomicparsley

and bit older, https://superuser.com/questions/962721/what-kind-of-metadata-can-be-stored-in-m4a-files

**Comment by Jinestic** [comment]
@GrayGalaxy Issue doesn't seem to be fixed yet. Playlist still gets stuck indefinitely.

**Comment by GrayGalaxy** [comment]
@Jinestic I checked several times the download works fine for me. you just have to wait while it creates a zip file. As the list is very big, depending on the HDD / SSD speed zipping may take a while.

If the issue persists please wait for the next release.
